apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appmesh-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN }}
