# NOTE: When installing, please, update this file with the correct subdomain!

image:
  repository: typrone1/bookstoreapp_front-end
  tag: latest
serviceAccount:
  roleARN: arn:aws:iam::827539266883:role/bookstore-eks-jjnKsgUc-development-sa-front-end-role
api:
  url: https://api.dev.bookstore.huuty.xyz
  resource_api: https://resource-api.dev.bookstore.huuty.xyz/
  inventory_api: https://inventory-api.dev.bookstore.huuty.xyz/
  renting_api: https://renting-api.dev.bookstore.huuty.xyz/
  clients_api: https://clients-api.dev.bookstore.huuty.xyz/