service:
  type: LoadBalancer
persistence:
  enabled: true
  storageClassName: "gp2"
adminPassword: 'EKS!sAWSome'
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true