apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-bookstore
  region: ap-southeast-1
  version: "1.20"

vpc:
  cidr: 10.0.0.0/16
nodeGroups:
  - name: eks-bookstore-nodegroup
    instanceType: t2.micro
    desiredCapacity: 3
    privateNetworking: true
